//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public int Department_ID { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Owner_ID { get; set; }
    
        public virtual OWNER OWNER { get; set; }
    }
}
