//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int Reservation_ID { get; set; }
        public int No_Of_Adults { get; set; }
        public Nullable<int> No_Of_Childs { get; set; }
        public Nullable<System.DateTime> CheckIN_Date { get; set; }
        public System.DateTime CheckOUT_Date { get; set; }
        public int Room_ID { get; set; }
        public int Receptionist_ID { get; set; }
        public int Guest_ID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual RECEPTIONIST RECEPTIONIST { get; set; }
        public virtual ROOM ROOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
    }
}
