//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRoomViewModel
    {
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int NoOfAdults { get; set; }
        public int NoOfChilds { get; set; }
        public int Room { get; set; }
    
        public virtual ROOM ROOM1 { get; set; }
    }
}
