//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.ROLEEs = new HashSet<ROLEE>();
        }
    
        public int ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Address { get; set; }
        public int Age { get; set; }
        public System.DateTime Date_Of_Joining { get; set; }
        public decimal Salary { get; set; }
        public string Designation { get; set; }
        public string Mail_ID { get; set; }
        public int Dept_ID { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLEE> ROLEEs { get; set; }
    }
}
